better melpazoid, comments: add other package

diff --git a/.github/workflows/melpazoid.yml b/.github/workflows/melpazoid.yml
--- a/.github/workflows/melpazoid.yml
+++ b/.github/workflows/melpazoid.yml
@@ -33,12 +33,17 @@ jobs:
           EXIST_OK: true
         run: |
           echo $GITHUB_REF
-          if make -C ~/melpazoid |& tee output.log; then
-            if grep -q "Warning" output.log; then
-              echo "Warnings detected, failing workflow"
-              exit 1
-            fi
-          else
-            echo "Make command failed, failing workflow"
-            exit 1
+          make -C ~/melpazoid |& tee output.log
+          [ $? -ne 0 ] && { echo "Make command failed, failing workflow"; exit 1; }
+          if grep -q "Warning" output.log ; then
+            echo "Warnings detected, failing workflow" ; exit 1
+          fi
+          if grep -q ': error: ' output.log ; then
+            echo "Error detected, failing workflow" ; exit 1
+          fi
+          if grep -q ' with [melpazoid]' output.log ; then
+            echo "Melpazoid warning detected, failing workflow" ; exit 1
+          fi
+          if grep -q ' with checkdoc ' output.log ; then
+            echo "Checkdoc warning detected, failing workflow" ; exit 1
           fi
